import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Suspense } from "react";
import AuthenticatedHeader from "@/components/authenticated-header";
import { SessionProvider } from "@/lib/providers/dession-provider";
import { QueryProvider } from "@/lib/providers/query-provider";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const sourceMono = Source_Code_Pro({
	variable: "--font-source-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${sourceMono.variable}`}>
				<SessionProvider>
					<QueryProvider>
						<AntdRegistry>
							<AuthenticatedHeader />
							<Suspense>{children}</Suspense>
						</AntdRegistry>
					</QueryProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
